[install]
# Packages with native dependencies that need to be built
trustedDependencies = [
  "@tailwindcss/oxide",
  "esbuild",
  "maplibre-gl",
  "sharp",
  "simple-git-hooks",
  "unrs-resolver",
  "vue-demi",
  "workerd",
]
